import { Engineer, Evaluation, EvaluationCycle } from "./types";
import { EVALUATION_PARAMETERS } from "./constants";

export const MOCK_CYCLES: EvaluationCycle[] = [
  {
    id: "cycle_q3_2026",
    title: "Q3 2026 Engineering Performance Cycle",
    quarter: "Q3",
    year: 2026,
    status: "Active",
    startDate: "2026-07-01",
    endDate: "2026-09-30",
  },
  {
    id: "cycle_q2_2026",
    title: "Q2 2026 Engineering Evaluation",
    quarter: "Q2",
    year: 2026,
    status: "Completed",
    startDate: "2026-04-01",
    endDate: "2026-06-30",
  },
  {
    id: "cycle_q1_2026",
    title: "Q1 2026 Engineering Evaluation",
    quarter: "Q1",
    year: 2026,
    status: "Completed",
    startDate: "2026-01-01",
    endDate: "2026-03-31",
  },
];

export const MOCK_ENGINEERS: Engineer[] = [
  {
    id: "eng_1",
    fullName: "Aarav Sharma",
    employeeId: "ENG-101",
    email: "aarav.sharma@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    designation: "Staff Frontend Architect",
    departmentId: "dept_2",
    departmentName: "Frontend Architecture & UX",
    teamId: "team_2",
    teamName: "Design System & Web Apps",
    captainId: "user_cap_2",
    captainName: "Marcus Vance",
    joiningDate: "2022-03-15",
    experienceYears: 7.5,
    primarySkills: ["TypeScript", "Next.js", "Tailwind CSS", "React", "Web Performance"],
    secondarySkills: ["GraphQL", "Web Workers", "Wasm"],
    status: "Active",
    avgScore: 96.5,
    grade: "A+",
  },
  {
    id: "eng_2",
    fullName: "Priya Nair",
    employeeId: "ENG-102",
    email: "priya.nair@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80",
    designation: "Principal Distributed Systems Engineer",
    departmentId: "dept_3",
    departmentName: "Backend & Distributed Systems",
    teamId: "team_1",
    teamName: "API Gateway & Microservices",
    captainId: "user_cap_1",
    captainName: "Elena Rostova",
    joiningDate: "2021-08-01",
    experienceYears: 9.0,
    primarySkills: ["Go", "Distributed Systems", "gRPC", "Kafka", "PostgreSQL"],
    secondarySkills: ["Kubernetes", "eBPF", "Redis"],
    status: "Active",
    avgScore: 94.2,
    grade: "A",
  },
  {
    id: "eng_3",
    fullName: "Devon Miller",
    employeeId: "ENG-103",
    email: "devon.miller@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    designation: "Senior AI / Infrastructure Specialist",
    departmentId: "dept_4",
    departmentName: "AI & Machine Learning Infrastructure",
    teamId: "team_3",
    teamName: "LLM Pipeline & Inference",
    captainId: "user_cap_3",
    captainName: "Dr. Sarah Chen",
    joiningDate: "2023-01-10",
    experienceYears: 5.8,
    primarySkills: ["Python", "PyTorch", "vLLM", "CUDA", "FastAPI"],
    secondarySkills: ["Docker", "Triton Server", "MLflow"],
    status: "Active",
    avgScore: 91.0,
    grade: "A",
  },
  {
    id: "eng_4",
    fullName: "Sophia Rodriguez",
    employeeId: "ENG-104",
    email: "sophia.rodriguez@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=300&auto=format&fit=crop&q=80",
    designation: "Senior Platform SRE",
    departmentId: "dept_5",
    departmentName: "DevOps & Cloud Reliability",
    teamId: "team_4",
    teamName: "Kubernetes & Infrastructure",
    captainId: "user_cap_4",
    captainName: "David Miller",
    joiningDate: "2022-11-01",
    experienceYears: 6.2,
    primarySkills: ["Kubernetes", "Terraform", "AWS", "Prometheus", "Golang"],
    secondarySkills: ["ArgoCD", "Istio", "Python"],
    status: "Active",
    avgScore: 88.4,
    grade: "B+",
  },
  {
    id: "eng_5",
    fullName: "Kenji Tanaka",
    employeeId: "ENG-105",
    email: "kenji.tanaka@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
    designation: "Lead Data Engineer",
    departmentId: "dept_1",
    departmentName: "Core Platform Engineering",
    teamId: "team_5",
    teamName: "Data Lake & Analytics Engine",
    captainId: "user_cap_1",
    captainName: "Elena Rostova",
    joiningDate: "2021-04-12",
    experienceYears: 8.1,
    primarySkills: ["Apache Spark", "ClickHouse", "Python", "SQL", "Airflow"],
    secondarySkills: ["dbt", "Snowflake", "Iceberg"],
    status: "Active",
    avgScore: 89.5,
    grade: "B+",
  },
  {
    id: "eng_6",
    fullName: "Elena Rostova",
    employeeId: "ENG-106",
    email: "elena.rostova@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80",
    designation: "Engineering Captain & Principal Architect",
    departmentId: "dept_3",
    departmentName: "Backend & Distributed Systems",
    teamId: "team_1",
    teamName: "API Gateway & Microservices",
    captainId: "user_cap_1",
    captainName: "Elena Rostova",
    joiningDate: "2020-02-01",
    experienceYears: 12.0,
    primarySkills: ["System Design", "Go", "Java", "Architecture Leadership", "Strategy"],
    secondarySkills: ["PostgreSQL", "Kafka", "Cloud Security"],
    status: "Active",
    avgScore: 98.0,
    grade: "A+",
  },
  {
    id: "eng_7",
    fullName: "Lucas Vance",
    employeeId: "ENG-107",
    email: "lucas.vance@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80",
    designation: "Fullstack Engineer II",
    departmentId: "dept_2",
    departmentName: "Frontend Architecture & UX",
    teamId: "team_2",
    teamName: "Design System & Web Apps",
    captainId: "user_cap_2",
    captainName: "Marcus Vance",
    joiningDate: "2023-06-01",
    experienceYears: 3.5,
    primarySkills: ["React", "TypeScript", "Node.js", "GraphQL"],
    secondarySkills: ["Tailwind CSS", "Prisma"],
    status: "Active",
    avgScore: 82.0,
    grade: "B+",
  },
  {
    id: "eng_8",
    fullName: "Amara Oke",
    employeeId: "ENG-108",
    email: "amara.oke@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80",
    designation: "Backend Engineer II",
    departmentId: "dept_3",
    departmentName: "Backend & Distributed Systems",
    teamId: "team_1",
    teamName: "API Gateway & Microservices",
    captainId: "user_cap_1",
    captainName: "Elena Rostova",
    joiningDate: "2023-09-15",
    experienceYears: 4.0,
    primarySkills: ["Go", "PostgreSQL", "Docker", "REST APIs"],
    secondarySkills: ["Redis", "gRPC"],
    status: "Active",
    avgScore: 76.5,
    grade: "B",
  },
  {
    id: "eng_9",
    fullName: "Viktor Petrov",
    employeeId: "ENG-109",
    email: "viktor.petrov@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80",
    designation: "Security & Cloud Infrastructure Engineer",
    departmentId: "dept_5",
    departmentName: "DevOps & Cloud Reliability",
    teamId: "team_4",
    teamName: "Kubernetes & Infrastructure",
    captainId: "user_cap_4",
    captainName: "David Miller",
    joiningDate: "2024-01-15",
    experienceYears: 2.8,
    primarySkills: ["Python", "Security", "Vault", "Linux", "CI/CD"],
    secondarySkills: ["Bash", "AWS"],
    status: "In Review",
    avgScore: 68.4,
    grade: "C",
  },
  {
    id: "eng_10",
    fullName: "Chloe Dubois",
    employeeId: "ENG-110",
    email: "chloe.dubois@ledger.internal",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80",
    designation: "Junior AI Researcher",
    departmentId: "dept_4",
    departmentName: "AI & Machine Learning Infrastructure",
    teamId: "team_3",
    teamName: "LLM Pipeline & Inference",
    captainId: "user_cap_3",
    captainName: "Dr. Sarah Chen",
    joiningDate: "2024-03-01",
    experienceYears: 1.5,
    primarySkills: ["Python", "PyTorch", "Data Science"],
    secondarySkills: ["LangChain", "Vector DBs"],
    status: "Active",
    avgScore: 74.0,
    grade: "B",
  },
];

export const MOCK_EVALUATIONS: Evaluation[] = [
  {
    id: "eval_2026_q3_1",
    cycleId: "cycle_q3_2026",
    engineerId: "eng_1",
    engineerName: "Aarav Sharma",
    engineerEmail: "aarav.sharma@ledger.internal",
    engineerDesignation: "Staff Frontend Architect",
    engineerDepartment: "Frontend Architecture & UX",
    engineerPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80",
    reviewerName: "Marcus Vance",
    reviewerEmail: "marcus.vance@ledger.internal",
    reviewerRole: "Captain",
    evaluationDate: "2026-07-28",
    quarter: "Q3",
    year: 2026,
    overallScore: 96.5,
    percentage: 96.5,
    grade: "A+",
    gradeLabel: "Outstanding",
    rank: 1,
    status: "Completed",
    comments: "Aarav demonstrated exceptional leadership in upgrading our Design System to Next.js 15, reducing initial bundle size by 34%. He rigorously validated all AI-generated code snippets for security and performance.",
    createdAt: "2026-07-28T10:00:00Z",
    updatedAt: "2026-07-28T10:00:00Z",
    parameterScores: [
      {
        parameterId: "param_1",
        parameterKey: "ai_usage",
        parameterName: "AI Usage Guidelines",
        rating: 5,
        weight: 15,
        evidence: "Aarav created internal AI prompt templates for component generation while enforcing custom AST linter rules to block any hardcoded credentials or unverified dependencies.",
        improvementSuggestion: "Share the prompt engineering guidelines with cross-functional junior teams.",
      },
      {
        parameterId: "param_2",
        parameterKey: "engineering_knowledge",
        parameterName: "Engineering Knowledge",
        rating: 5,
        weight: 15,
        evidence: "Refactored key UI components into isolated client-side worker threads, eliminating frame drops during heavy data renders.",
        improvementSuggestion: "Publish internal RFC on Web Workers architecture.",
      },
      {
        parameterId: "param_3",
        parameterKey: "subject_expertise",
        parameterName: "Subject Expertise",
        rating: 5,
        weight: 15,
        evidence: "Recognized across the engineering org as the primary subject authority on browser layout engines and accessibility (WCAG 2.1 AAA).",
        improvementSuggestion: "Continue guiding accessibility audits across sub-teams.",
      },
      {
        parameterId: "param_4",
        parameterKey: "communication",
        parameterName: "Communication",
        rating: 4,
        weight: 10,
        evidence: "Wrote clear tech specs for the Design System migration. Moderated bi-weekly architecture syncs with active engagement.",
        improvementSuggestion: "Encourage more async decision log updates in Notion.",
      },
      {
        parameterId: "param_5",
        parameterKey: "team_player",
        parameterName: "Team Player & Mentorship",
        rating: 5,
        weight: 15,
        evidence: "Mentored 3 junior frontend engineers through structured weekly pair programming sessions and PR code reviews.",
        improvementSuggestion: "Formalize the frontend mentorship curriculum.",
      },
      {
        parameterId: "param_6",
        parameterKey: "innovation",
        parameterName: "Innovation & Automation",
        rating: 5,
        weight: 10,
        evidence: "Built an automated visual regression testing workflow using Playwright & GitHub Actions that caught 18 UI bugs before QA release.",
        improvementSuggestion: "Expand visual diff suite to mobile responsive break points.",
      },
      {
        parameterId: "param_7",
        parameterKey: "delivery",
        parameterName: "Delivery & Execution",
        rating: 5,
        weight: 10,
        evidence: "Achieved 100% sprint deliverable velocity for Q2 and Q3 with zero high-severity production rollbacks.",
        improvementSuggestion: "Keep maintaining realistic sprint capacity buffers.",
      },
      {
        parameterId: "param_8",
        parameterKey: "learning",
        parameterName: "Continuous Learning",
        rating: 4,
        weight: 10,
        evidence: "Completed advanced WebAssembly certification and delivered a tech talk on Wasm performance in React.",
        improvementSuggestion: "Explore Rust-to-Wasm integration for complex data transformations.",
      },
    ],
  },
  {
    id: "eval_2026_q3_2",
    cycleId: "cycle_q3_2026",
    engineerId: "eng_2",
    engineerName: "Priya Nair",
    engineerEmail: "priya.nair@ledger.internal",
    engineerDesignation: "Principal Distributed Systems Engineer",
    engineerDepartment: "Backend & Distributed Systems",
    engineerPhoto: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80",
    reviewerName: "Elena Rostova",
    reviewerEmail: "elena.rostova@ledger.internal",
    reviewerRole: "Captain",
    evaluationDate: "2026-07-25",
    quarter: "Q3",
    year: 2026,
    overallScore: 94.2,
    percentage: 94.2,
    grade: "A",
    gradeLabel: "Excellent",
    rank: 2,
    status: "Completed",
    comments: "Priya architected the new high-throughput gRPC event gateway handling over 120k requests/sec at under 4ms latency p99. Exceptional technical ownership and safety awareness.",
    createdAt: "2026-07-25T14:30:00Z",
    updatedAt: "2026-07-25T14:30:00Z",
    parameterScores: [
      {
        parameterId: "param_1",
        parameterKey: "ai_usage",
        parameterName: "AI Usage Guidelines",
        rating: 4,
        weight: 15,
        evidence: "Uses GitHub Copilot effectively for boilerplate generation while conducting rigorous manual peer reviews of all AI suggested SQL queries.",
        improvementSuggestion: "Benchmark AI-suggested Go concurrency primitives under high load.",
      },
      {
        parameterId: "param_2",
        parameterKey: "engineering_knowledge",
        parameterName: "Engineering Knowledge",
        rating: 5,
        weight: 15,
        evidence: "Deep mastery of Go lock-free data structures, memory pool recycling, and eBPF network telemetry.",
        improvementSuggestion: "Document low-level memory allocation tricks in team wiki.",
      },
      {
        parameterId: "param_3",
        parameterKey: "subject_expertise",
        parameterName: "Subject Expertise",
        rating: 5,
        weight: 15,
        evidence: "Led the outage recovery analysis and re-engineered our distributed consensus fallback mechanism.",
        improvementSuggestion: "Lead quarterly chaos engineering drills.",
      },
      {
        parameterId: "param_4",
        parameterKey: "communication",
        parameterName: "Communication",
        rating: 4,
        weight: 10,
        evidence: "High quality post-mortems and clear architecture diagrams in Mermaid format.",
        improvementSuggestion: "Simplify non-technical summaries for executive updates.",
      },
      {
        parameterId: "param_5",
        parameterKey: "team_player",
        parameterName: "Team Player & Mentorship",
        rating: 5,
        weight: 15,
        evidence: "Always available to assist team members with tricky deadlock issues and concurrency bugs.",
        improvementSuggestion: "Delegate some on-call triaging to mid-level engineers.",
      },
      {
        parameterId: "param_6",
        parameterKey: "innovation",
        parameterName: "Innovation & Automation",
        rating: 5,
        weight: 10,
        evidence: "Designed an automated load generator that simulates 500k active websocket connections for load testing.",
        improvementSuggestion: "Open-source the load generation toolkit.",
      },
      {
        parameterId: "param_7",
        parameterKey: "delivery",
        parameterName: "Delivery & Execution",
        rating: 5,
        weight: 10,
        evidence: "Delivered the gRPC API migration 2 weeks ahead of target schedule.",
        improvementSuggestion: "Maintain great delivery pace.",
      },
      {
        parameterId: "param_8",
        parameterKey: "learning",
        parameterName: "Continuous Learning",
        rating: 4,
        weight: 10,
        evidence: "Regularly reviews distributed systems research papers (VLDB, SIGMOD) and shares summaries with the backend team.",
        improvementSuggestion: "Host a monthly paper reading group.",
      },
    ],
  },
  {
    id: "eval_2026_q3_3",
    cycleId: "cycle_q3_2026",
    engineerId: "eng_3",
    engineerName: "Devon Miller",
    engineerEmail: "devon.miller@ledger.internal",
    engineerDesignation: "Senior AI / Infrastructure Specialist",
    engineerDepartment: "AI & Machine Learning Infrastructure",
    engineerPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
    reviewerName: "Dr. Sarah Chen",
    reviewerEmail: "sarah.chen@ledger.internal",
    reviewerRole: "Captain",
    evaluationDate: "2026-07-26",
    quarter: "Q3",
    year: 2026,
    overallScore: 91.0,
    percentage: 91.0,
    grade: "A",
    gradeLabel: "Excellent",
    rank: 3,
    status: "Completed",
    comments: "Devon led the optimization of our vLLM inference server, cutting token generation latency by 42% while implementing strict data privacy filters.",
    createdAt: "2026-07-26T11:20:00Z",
    updatedAt: "2026-07-26T11:20:00Z",
    parameterScores: [
      {
        parameterId: "param_1",
        parameterKey: "ai_usage",
        parameterName: "AI Usage Guidelines",
        rating: 5,
        weight: 15,
        evidence: "Exemplary AI hygiene. Established PII redaction layer before sending prompts to external model endpoints.",
        improvementSuggestion: "Audit edge-case token leakage patterns.",
      },
      {
        parameterId: "param_2",
        parameterKey: "engineering_knowledge",
        parameterName: "Engineering Knowledge",
        rating: 4,
        weight: 15,
        evidence: "Strong understanding of GPU memory management, PagedAttention, and Triton custom kernels.",
        improvementSuggestion: "Further streamline Python-to-C++ binding layer.",
      },
      {
        parameterId: "param_3",
        parameterKey: "subject_expertise",
        parameterName: "Subject Expertise",
        rating: 5,
        weight: 15,
        evidence: "Core owner of model quantization (AWQ / FP8) pipeline. Reduced VRAM footprint by half.",
        improvementSuggestion: "Evaluate FP4 precision benchmarks.",
      },
      {
        parameterId: "param_4",
        parameterKey: "communication",
        parameterName: "Communication",
        rating: 4,
        weight: 10,
        evidence: "Clear documentation on model deployment procedures and GPU cluster scaling policies.",
        improvementSuggestion: "Improve response time on cross-team Slack channels.",
      },
      {
        parameterId: "param_5",
        parameterKey: "team_player",
        parameterName: "Team Player & Mentorship",
        rating: 4,
        weight: 15,
        evidence: "Collaborated effectively with the security team to complete compliance certification for model weights.",
        improvementSuggestion: "Conduct more pair programming sessions with junior AI engineers.",
      },
      {
        parameterId: "param_6",
        parameterKey: "innovation",
        parameterName: "Innovation & Automation",
        rating: 5,
        weight: 10,
        evidence: "Automated model evaluation benchmarks against standard evaluation datasets (MMLU, HumanEval).",
        improvementSuggestion: "Integrate automated benchmark reports into PR checks.",
      },
      {
        parameterId: "param_7",
        parameterKey: "delivery",
        parameterName: "Delivery & Execution",
        rating: 4,
        weight: 10,
        evidence: "Met all core milestone deadlines for the Q2 inference upgrade.",
        improvementSuggestion: "Break down large epics into smaller 2-day deliverables.",
      },
      {
        parameterId: "param_8",
        parameterKey: "learning",
        parameterName: "Continuous Learning",
        rating: 5,
        weight: 10,
        evidence: "Attended NeurIPS 2025 and conducted a comprehensive tech summary for the engineering department.",
        improvementSuggestion: "Keep leading AI research roundtables.",
      },
    ],
  },
  {
    id: "eval_2026_q3_4",
    cycleId: "cycle_q3_2026",
    engineerId: "eng_8",
    engineerName: "Amara Oke",
    engineerEmail: "amara.oke@ledger.internal",
    engineerDesignation: "Backend Engineer II",
    engineerDepartment: "Backend & Distributed Systems",
    engineerPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80",
    reviewerName: "Elena Rostova",
    reviewerEmail: "elena.rostova@ledger.internal",
    reviewerRole: "Captain",
    evaluationDate: "2026-07-27",
    quarter: "Q3",
    year: 2026,
    overallScore: 76.5,
    percentage: 76.5,
    grade: "B",
    gradeLabel: "Good",
    rank: 4,
    status: "Completed",
    comments: "Amara shows steady progress in Golang backend development and unit testing. She should focus on deepening system architecture understanding and proactive communication during complex migrations.",
    createdAt: "2026-07-27T09:15:00Z",
    updatedAt: "2026-07-27T09:15:00Z",
    parameterScores: [
      {
        parameterId: "param_1",
        parameterKey: "ai_usage",
        parameterName: "AI Usage Guidelines",
        rating: 4,
        weight: 15,
        evidence: "Leverages AI tools effectively for test generation; validates outputs consistently before committing.",
        improvementSuggestion: "Practice prompt refinement for complex domain logic.",
      },
      {
        parameterId: "param_2",
        parameterKey: "engineering_knowledge",
        parameterName: "Engineering Knowledge",
        rating: 3,
        weight: 15,
        evidence: "Writes clean modular Go code for CRUD services; needs deeper grasp of database index tuning and locking mechanisms.",
        improvementSuggestion: "Take database internal architecture course.",
      },
      {
        parameterId: "param_3",
        parameterKey: "subject_expertise",
        parameterName: "Subject Expertise",
        rating: 4,
        weight: 15,
        evidence: "Good ownership of the user auth and token validation microservice.",
        improvementSuggestion: "Expand ownership to payment integration modules.",
      },
      {
        parameterId: "param_4",
        parameterKey: "communication",
        parameterName: "Communication",
        rating: 3,
        weight: 10,
        evidence: "Participates in daily standups; needs to communicate early when encountering blocked dependencies.",
        improvementSuggestion: "Raise blockers immediately in standup or Slack rather than waiting.",
      },
      {
        parameterId: "param_5",
        parameterKey: "team_player",
        parameterName: "Team Player & Mentorship",
        rating: 4,
        weight: 15,
        evidence: "Always positive and eager to assist team members with testing setup.",
        improvementSuggestion: "Participate more actively in peer PR reviews.",
      },
      {
        parameterId: "param_6",
        parameterKey: "innovation",
        parameterName: "Innovation & Automation",
        rating: 3,
        weight: 10,
        evidence: "Suggested helpful mock generator scripts for API integration tests.",
        improvementSuggestion: "Proactively propose CI build optimizations.",
      },
      {
        parameterId: "param_7",
        parameterKey: "delivery",
        parameterName: "Delivery & Execution",
        rating: 4,
        weight: 10,
        evidence: "Consistently completes assigned sprint tickets within estimated timeframes.",
        improvementSuggestion: "Refine ticket estimation accuracy for edge cases.",
      },
      {
        parameterId: "param_8",
        parameterKey: "learning",
        parameterName: "Continuous Learning",
        rating: 4,
        weight: 10,
        evidence: "Active participant in team technical reading sessions; completed Golang concurrency course.",
        improvementSuggestion: "Present a lightning talk on Go channels.",
      },
    ],
  },
  {
    id: "eval_2026_q3_5",
    cycleId: "cycle_q3_2026",
    engineerId: "eng_9",
    engineerName: "Viktor Petrov",
    engineerEmail: "viktor.petrov@ledger.internal",
    engineerDesignation: "Security & Cloud Infrastructure Engineer",
    engineerDepartment: "DevOps & Cloud Reliability",
    engineerPhoto: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80",
    reviewerName: "David Miller",
    reviewerEmail: "david.miller@ledger.internal",
    reviewerRole: "Captain",
    evaluationDate: "2026-07-20",
    quarter: "Q3",
    year: 2026,
    overallScore: 68.4,
    percentage: 68.4,
    grade: "C",
    gradeLabel: "Needs Improvement",
    rank: 5,
    status: "Completed",
    comments: "Viktor possesses solid raw technical skills in Linux systems, but requires structured growth in team communication, thorough documentation, and verifying automated outputs before committing production Terraform scripts.",
    createdAt: "2026-07-20T16:00:00Z",
    updatedAt: "2026-07-20T16:00:00Z",
    parameterScores: [
      {
        parameterId: "param_1",
        parameterKey: "ai_usage",
        parameterName: "AI Usage Guidelines",
        rating: 2,
        weight: 15,
        evidence: "Committed AI-suggested Terraform code without verifying IAM policy permissions, causing a temporary staging permission lockdown.",
        improvementSuggestion: "Mandatory double-verification of all AI-generated cloud infrastructure scripts before applying plan.",
      },
      {
        parameterId: "param_2",
        parameterKey: "engineering_knowledge",
        parameterName: "Engineering Knowledge",
        rating: 4,
        weight: 15,
        evidence: "Good understanding of kernel parameters, Linux networking, and Vault secret engines.",
        improvementSuggestion: "Apply clean code principles to shell and Python automation scripts.",
      },
      {
        parameterId: "param_3",
        parameterKey: "subject_expertise",
        parameterName: "Subject Expertise",
        rating: 3,
        weight: 15,
        evidence: "Capable of troubleshooting complex network routing bugs under guidance.",
        improvementSuggestion: "Take full ownership of staging environment maintenance.",
      },
      {
        parameterId: "param_4",
        parameterKey: "communication",
        parameterName: "Communication",
        rating: 2,
        weight: 10,
        evidence: "Documentation for new Vault secret rotation workflow was missing setup steps and caused friction for developers.",
        improvementSuggestion: "Follow the standard team README & spec template for all infrastructure changes.",
      },
      {
        parameterId: "param_5",
        parameterKey: "team_player",
        parameterName: "Team Player & Mentorship",
        rating: 3,
        weight: 15,
        evidence: "Willing to assist when asked, but rarely engages in team discussions or architectural planning.",
        improvementSuggestion: "Actively participate in daily standup syncs and team retrospectives.",
      },
      {
        parameterId: "param_6",
        parameterKey: "innovation",
        parameterName: "Innovation & Automation",
        rating: 3,
        weight: 10,
        evidence: "Created bash script for log archiving.",
        improvementSuggestion: "Migrate legacy shell scripts to idempotent Ansible / Terraform workflows.",
      },
      {
        parameterId: "param_7",
        parameterKey: "delivery",
        parameterName: "Delivery & Execution",
        rating: 3,
        weight: 10,
        evidence: "Sprint deliverables frequently carried over into subsequent sprints due to unplanned re-work.",
        improvementSuggestion: "Set explicit daily milestones and seek captain review early.",
      },
      {
        parameterId: "param_8",
        parameterKey: "learning",
        parameterName: "Continuous Learning",
        rating: 3,
        weight: 10,
        evidence: "Started CKA certification preparation.",
        improvementSuggestion: "Complete CKA exam by end of Q3.",
      },
    ],
  },
];
